version: '3.4'

services:
    book-registry:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - 5000:80 

    redis:
        container_name: redis
        image: redislabs/rejson:latest
        volumes:
            - ./book_data:/data 
        ports:
            - 6379:6379
        command: redis-server /data/redis.conf --loadmodule /usr/lib/redis/modules/rejson.so